### PR TITLE
Adding tile names translation + possibility to use expansion symbols

### PR DESCRIPTION
**Pull request by ilujito2**
**Attention : this is not _just_ a translation related PR.**
There are also few code changes. Of course, feel free to reject, this is just a proposition.

**TL;DR:** This PR proposes the following changes:
 - Adding translation of the expansion names exposed during tiles setup
 - Adding the possibility to use expansion Symbols instead of names (configurable per language basis)
 _
 - Applying the use of these Symbols to French translation in ui.json file
 - Adding the use of expansion symbols as well in the French mission json files (for consistency)

Through this PR, the feature is _available_ for all languages, but it's only _applied_ to French.
Note: I will sent a PR as well for SagaTranslatorModern (in case this PR is accepted).

--------------
Information about a change I did to your previous code and that I wanted to share :

The use of the expansion symbols was already available (using "ImperialAssaultSymbols SDF" font) but it was forced to be of color Red (as the rest of the Icons). I searched in all the json files and I couldn't find any reference to these expansion symbols. I therefore removed the forced color (as it should not have any impact, as they were not used), so that symbols can now be used anywhere, inheriting the color of where they will be used (i.e. : orange for Tiles setup, white in the missions texts, yellow in tutorial1...)
Once again, of course, feel free to reject this if you think it's not appropriate.

--------------
Side note: ui.json files were only changed for EN and FR. For other languages, they will default to EN when not set.

--------------
More details about the feature changes:

My initial concern was that during Tile setup, "CORE 1A" does not make sense in French ("CORE" isn't French).
Adding translation now allows to have French translation:

image

However, even though the word "Base" is now in French, it's not really elegant (it's not clear what it means. I would have to use "Jeu de base"  and then tile setup screen would be unreadable...).
So, that's where the use of symbols makes things now a lot clearer (and most importantly, **totally language independent**).
Using the "{0}" notation in the ui.json file, it now allows to have:

image

Once changed for the tile setup, I also changed the French mission json files.
Couple examples of the end result:

- in Hoth14:
image

- in Tutorial1:
image

- in Bespin2:
image

Hoping that you will find this PR proposition usefull,
Do not hesitate if you have any comments
ilu

### CODE REVIEW

**Comment by Noldorion** [comment]
Hey there,

just one comment: I think this is pretty cool, and if you have the time right now, I wouldn't mind if you were willing to change it in the remaining languages. I could provide you with the translations necessary for the search & replace, but only the week after next.

All the best,
Noldorion

**Comment by ilujito2** [comment]
> Hey there,
> 
> just one comment: I think this is pretty cool, and if you have the time right now, I wouldn't mind if you were willing to change it in the remaining languages. I could provide you with the translations necessary for the search & replace, but only the week after next.
> 
> All the best, Noldorion

If this PR gets accepted, doing the change for _tiles setup_ is super easy and quick (it's just changing the new fields in ui.json for each language).
For the mission files, it will require a little bit more time, but it's totally doable.
I think it's best to do all this in another PR, following this one (if this one is accepted of course :-) )

Cheers,
ilu

**Comment by jph33** [comment]
Hi everyone and thank you for all the provided work.
I think there is stille some places where the tiles symbols are not considered:
image
Am i wrong?

**Comment by ilujito2** [comment]
You're right ! I totally missed that there was a "Tiles" button during setup phase that was also showing similar information.
I'll try to quickly find how to fix this.

**Comment by ilujito2** [comment]
@jph33 : I just created a new PR (https://github.com/GlowPuff/ImperialCommander2/pull/101) to fix this.

Side note: So you're using the French translation of the app ? If so, do not hesitate to let me know if you see any typo in the translation (via BGG).

Cheers,

**Comment by jph33** [comment]
@ilujito2 Comptes sur moi! Je suis la personne qui a fait la première traduction de l'application en FR. En tout cas bravo à toi pour avoir repris le flambeau et traduit tout le reste et corriger l'existant!

**Pull request merged**
